# Generated by Django 4.0 on 2022-04-12 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=30, verbose_name='Condition')),
            ],
        ),
        migrations.CreateModel(
            name='Coupe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=30, verbose_name='Coupe')),
            ],
        ),
        migrations.CreateModel(
            name='Fuel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20, verbose_name='Fuel')),
            ],
        ),
        migrations.CreateModel(
            name='Gearbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=30, verbose_name='Gearbox')),
            ],
        ),
        migrations.CreateModel(
            name='NumberOfDoors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_doors', models.CharField(max_length=10, verbose_name='Number of doors')),
            ],
        ),
        migrations.CreateModel(
            name='TypeExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100, verbose_name='Type extra')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100, verbose_name='Model')),
                ('price', models.IntegerField(verbose_name='Price')),
                ('price_negotiable', models.BooleanField(blank=True, null=True, verbose_name='Price negotiable')),
                ('year_made', models.IntegerField(verbose_name='Year')),
                ('horsepower', models.IntegerField(blank=True, null=True, verbose_name='Horsepower')),
                ('engine_size', models.IntegerField(blank=True, null=True, verbose_name='Engine size')),
                ('mileage', models.IntegerField(verbose_name='Mileage')),
                ('color', models.CharField(blank=True, max_length=30, null=True, verbose_name='Color')),
                ('new_importation', models.BooleanField(blank=True, null=True, verbose_name='New importation')),
                ('located_at', models.CharField(max_length=30, verbose_name='Located at')),
                ('more_info', models.TextField(blank=True, null=True, verbose_name='More information')),
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user_profile.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Extra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extra', models.CharField(max_length=100, verbose_name='Extra')),
                ('type_extra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.typeextra')),
            ],
        ),
    ]
