# Generated by Django 4.0 on 2022-04-12 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='extras',
            field=models.ManyToManyField(blank=True, to='post.Extra'),
        ),
    ]
