# Generated by Django 4.0 on 2022-04-12 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_post_extras'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='coupe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='post.coupe'),
        ),
    ]
