# Generated by Django 4.0 on 2022-04-13 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_post_condition_post_fuel_post_gearbox_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='main_picture',
            field=models.ImageField(blank=True, null=True, upload_to='post_pictures', verbose_name='Main picture'),
        ),
    ]
