# Generated by Django 4.0 on 2022-04-15 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_post_picture_10_post_picture_2_post_picture_3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gearbox',
            name='type',
            field=models.CharField(max_length=30, verbose_name='Transmission'),
        ),
    ]
