# Generated by Django 4.0 on 2022-04-17 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_remove_extra_type_extra'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TypeExtra',
        ),
    ]
