# Generated by Django 4.0 on 2022-04-18 18:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0010_delete_typeextra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='main_picture',
            field=models.ImageField(blank=True, default='static/images/default_car.png', null=True, upload_to='post_pictures', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg'])], verbose_name='Main picture'),
        ),
    ]
