# Generated by Django 4.0 on 2022-04-19 18:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0013_alter_post_main_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='picture_10',
            field=models.ImageField(blank=True, default='post_pictures/default_car.jpg', null=True, upload_to='post_pictures', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg'])], verbose_name='10'),
        ),
        migrations.AlterField(
            model_name='post',
            name='picture_2',
            field=models.ImageField(blank=True, default='post_pictures/default_car.jpg', null=True, upload_to='post_pictures', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg'])], verbose_name='2'),
        ),
        migrations.AlterField(
            model_name='post',
            name='picture_3',
            field=models.ImageField(blank=True, default='post_pictures/default_car.jpg', null=True, upload_to='post_pictures', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg'])], verbose_name='3'),
        ),
        migrations.AlterField(
            model_name='post',
            name='picture_4',
            field=models.ImageField(blank=True, default='post_pictures/default_car.jpg', null=True, upload_to='post_pictures', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg'])], verbose_name='4'),
        ),
        migrations.AlterField(
            model_name='post',
            name='picture_5',
            field=models.ImageField(blank=True, default='post_pictures/default_car.jpg', null=True, upload_to='post_pictures', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg'])], verbose_name='5'),
        ),
        migrations.AlterField(
            model_name='post',
            name='picture_6',
            field=models.ImageField(blank=True, default='post_pictures/default_car.jpg', null=True, upload_to='post_pictures', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg'])], verbose_name='6'),
        ),
        migrations.AlterField(
            model_name='post',
            name='picture_7',
            field=models.ImageField(blank=True, default='post_pictures/default_car.jpg', null=True, upload_to='post_pictures', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg'])], verbose_name='7'),
        ),
        migrations.AlterField(
            model_name='post',
            name='picture_8',
            field=models.ImageField(blank=True, default='post_pictures/default_car.jpg', null=True, upload_to='post_pictures', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg'])], verbose_name='8'),
        ),
        migrations.AlterField(
            model_name='post',
            name='picture_9',
            field=models.ImageField(blank=True, default='post_pictures/default_car.jpg', null=True, upload_to='post_pictures', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg'])], verbose_name='9'),
        ),
    ]
