# Generated by Django 4.0 on 2022-04-23 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0014_alter_post_picture_10_alter_post_picture_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='new_importation',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='New importation'),
        ),
        migrations.AlterField(
            model_name='post',
            name='price_negotiable',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Price negotiable'),
        ),
    ]
