# Generated by Django 4.0 on 2022-05-10 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0016_post_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created']},
        ),
    ]
