# Generated by Django 4.0 on 2022-05-10 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_us', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='seen',
            field=models.BooleanField(default=False, verbose_name='Seen'),
        ),
    ]
