# Generated by Django 4.0 on 2022-04-20 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0014_alter_post_picture_10_alter_post_picture_2_and_more'),
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='post_follows',
            field=models.ManyToManyField(to='post.Post'),
        ),
    ]
