# Generated by Django 4.0 on 2022-04-05 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='profile_pics/default_profile_pic.jpg', upload_to='profile_pics'),
        ),
    ]
